# Mission
CREW_SIZE = 4
MISSION_DURATION_SOLS = 450
GROWING_AREA_M2 = 50

# Mars environment
MARS_GRAVITY = 3.72  # m/s²
MARS_SOLAR_IRRADIANCE_MAX = 590  # W/m²
MARS_SOL_LENGTH_HOURS = 24.62
MARS_ATMO_CO2_PERCENT = 95.3
MARS_SURFACE_TEMP_AVG = -60  # °C
MARS_COMMS_DELAY_MIN = 4  # minutes one-way
MARS_COMMS_DELAY_MAX = 24

# Greenhouse
GREENHOUSE_TEMP_TARGET = 22  # °C
GREENHOUSE_HUMIDITY_TARGET = 70  # %
GREENHOUSE_CO2_TARGET = 1200  # ppm
GREENHOUSE_PRESSURE = 101.3  # kPa
GREENHOUSE_PHOTOPERIOD_HOURS = 18
GREENHOUSE_PAR_TARGET = 400  # µmol/m²/s
GREENHOUSE_WATER_BUDGET_L = 1000  # initial
GREENHOUSE_WATER_RECYCLE_EFFICIENCY = 0.90
GREENHOUSE_POWER_BUDGET_KW = 20

# Nutrition (per astronaut per day, approximate NASA values)
DAILY_CALORIES_KCAL = 2800
DAILY_PROTEIN_G = 70
DAILY_FAT_G = 70  # ~25% of 2800 kcal
DAILY_FIBER_G = 25
DAILY_VITAMIN_C_MG = 90
DAILY_VITAMIN_K_UG = 120
DAILY_FOLATE_UG = 400
DAILY_CALCIUM_MG = 1200  # higher for spaceflight
DAILY_IRON_MG = 8
DAILY_POTASSIUM_MG = 3400
DAILY_VITAMIN_A_UG_RAE = 900

# Simulation
SIMULATION_TICK_HOURS = 6  # agent runs every 6 simulated hours
DUST_STORM_PROBABILITY_PER_SOL = 0.005
DISEASE_PROBABILITY_PER_SOL = 0.002

# Sensor noise parameters
SENSOR_TEMP_NOISE_STD = 0.5  # °C
SENSOR_HUMIDITY_NOISE_STD = 2.0  # %
SENSOR_CO2_NOISE_STD = 20.0  # ppm
SENSOR_PAR_NOISE_STD = 10.0  # µmol/m²/s
SENSOR_PH_NOISE_STD = 0.1
SENSOR_EC_NOISE_STD = 0.05  # mS/cm
SENSOR_FAILURE_PROBABILITY = 0.02  # per reading
SENSOR_STALENESS_MAX_TICKS = 2

# Zone configuration
NUM_ZONES = 6
ZONE_AREA_M2 = GROWING_AREA_M2 / NUM_ZONES  # ~8.33 m² each

# Power subsystem defaults (kW)
POWER_LIGHTING_PER_ZONE_KW = 1.5
POWER_HEATING_KW = 4.0
POWER_PUMPS_KW = 1.0
POWER_MONITORING_KW = 0.5
POWER_LIFE_SUPPORT_KW = 3.0

# Battery
BATTERY_CAPACITY_KWH = 100.0
BATTERY_INITIAL_CHARGE = 0.80  # 80%
