import type { SimState, NutritionData } from "./types";

const makeZone = (
  id: string,
  temp: number,
  humidity: number,
  co2: number,
  par: number,
  priority: SimState["zones"][0]["priority"] = "normal",
  quarantined = false,
) => ({
  zone_id: id,
  temperature: temp,
  humidity,
  co2_ppm: co2,
  par_level: par,
  lighting_on: true,
  irrigation_rate: 2.5,
  is_quarantined: quarantined,
  priority,
  crops: [
    { name: "Lettuce", growth_stage: "vegetative", days_planted: 12, health: 88, biomass_g: 340, days_to_harvest: 8 },
    { name: "Tomato", growth_stage: "flowering", days_planted: 45, health: 72, biomass_g: 1200, days_to_harvest: 25 },
    { name: "Radish", growth_stage: "seedling", days_planted: 3, health: 95, biomass_g: 45, days_to_harvest: 22 },
  ],
  environment: {
    sol: 47,
    is_daytime: true,
    external_temp: -63,
    solar_irradiance: 580,
    dust_opacity: 0.4,
    pressure_kpa: 0.636,
    o2_percent: 0.13,
  },
  resources: {
    water_reservoir_l: 1842,
    ph: 6.2,
    ec: 1.8,
    power_generation_kw: 15.2,
    power_consumption_kw: 12.8,
    battery_percent: 78,
  },
});

export const MOCK_STATE: SimState = {
  sol: 47,
  tick: 2,
  total_ticks: 188,
  is_daytime: true,
  environment: {
    external_temp_c: -63,
    solar_irradiance: 580,
    dust_opacity_tau: 0.4,
    dust_storm_active: false,
    dust_storm_remaining_sols: 0,
    disease_active: false,
    disease_zone_id: null,
    power_failure_active: false,
    pressure_kpa: 0.636,
    o2_percent: 0.13,
  },
  resources: {
    water_reservoir_l: 1842,
    water_consumed_today_l: 58,
    nutrient_ph: 6.2,
    nutrient_ec: 1.8,
    power_generation_kw: 15.2,
    power_consumption_kw: 12.8,
    battery_charge_kwh: 78,
    battery_percent: 78,
    solar_panel_efficiency: 0.92,
  },
  zones: [
    makeZone("A", 24.2, 68, 820, 450),
    makeZone("B", 23.8, 72, 790, 430, "high"),
    makeZone("C", 22.1, 65, 850, 410),
    makeZone("D", 25.0, 70, 810, 440, "normal", true),
    makeZone("E", 23.5, 67, 830, 420, "low"),
    makeZone("F", 21.8, 74, 800, 460),
  ],
  event_log_count: 23,
};

export const MOCK_NUTRITION: NutritionData = {
  vitamin_c_mg: { daily_production: 45, daily_requirement: 90, coverage_percent: 50 },
  vitamin_a_mcg: { daily_production: 700, daily_requirement: 900, coverage_percent: 77.8 },
  vitamin_k_mcg: { daily_production: 95, daily_requirement: 120, coverage_percent: 79.2 },
  folate_mcg: { daily_production: 320, daily_requirement: 400, coverage_percent: 80 },
  potassium_mg: { daily_production: 3200, daily_requirement: 4700, coverage_percent: 68.1 },
  calcium_mg: { daily_production: 800, daily_requirement: 1000, coverage_percent: 80 },
  iron_mg: { daily_production: 12, daily_requirement: 18, coverage_percent: 66.7 },
  fiber_g: { daily_production: 20, daily_requirement: 28, coverage_percent: 71.4 },
  protein_g: { daily_production: 35, daily_requirement: 50, coverage_percent: 70 },
  calories_kcal: { daily_production: 1600, daily_requirement: 2500, coverage_percent: 64 },
  overall_min_coverage_percent: 50,
};
